### ISSUE TITLE
logthreads and logqthreads seem to behave similarly

### ISSUE THREAD

**Issue by biona001** [tro3/ThreadPools.jl#13]
Hello, I tested a for loop with the `logthreads` and `logqthreads` macro, but the resulting plot seem to behave quite similarly:

`logthreads`:
![logthreads](https://user-images.githubusercontent.com/16760873/85798650-a7b1a700-b6f2-11ea-93e0-36e451ed5ea7.png)

`logqthreads`:
![logqthreads](https://user-images.githubusercontent.com/16760873/85798661-ac765b00-b6f2-11ea-87d0-f9a64573d90a.png)

I expected each thread in `logqthreads` to be roughly the same length. Did I misunderstand something or is this a bug? There figures are produced at the end of [this notebook](https://github.com/biona001/MendelImpute/blob/master/data/1000_genome_phase3_v5/filtered/Impute_untyped_chrom18.ipynb). Sorry I didn't provide a MWE since this is quite complicated to generate.

**Comment by tro3** [comment]
You are absolutely correct!  A couple logged version macro invocations got swapped - `logqthreads` is one.  I will fix now and issue a new revision.

In the meantime, you can generate the correct macro with:


```julia
import ThreadPools: _pthread_macro, LoggedQueuePool, pwith, tforeach

macro logqthreads_fixed(args...)
  return _pthread_macro(LoggedQueuePool(1), true, args...)
end

pool = @logqthreads_fixed for w in 1:windows
  ...
```

**Comment by tro3** [comment]
Now updated and released:

```
 pkg> update ThreadPools
...
 [b189fb0b] ↑ ThreadPools v1.1.0 ⇒ v1.1.1
```

Let me know if you have any trouble, and thanks for the feedback.
