### ISSUE TITLE
tmap using wrong memory?

### ISSUE THREAD

**Issue by robsmith11** [tro3/ThreadPools.jl#23]
I'm getting random bad results with tmap:
```
julia> versioninfo()
Julia Version 1.7.0-DEV.383
Commit bf15b706e9* (2021-01-26 04:39 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: AMD Ryzen 7 4700U with Radeon Graphics
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, znver2)

julia> tmap(x->2*x, 1:3)
3-element Vector{Int64}:
               2
               4
 140281846350176

julia> tmap(x->2*x, 1:6)
6-element Vector{Int64}:
               2
               4
 140278942196016
 140281753542688
 140281849890992
 140278986200064

julia> tmap(x->2*x, 1:8)
8-element Vector{Int64}:
  2
  4
  6
  8
 10
 12
 14
 16

```

EDIT:
I upgraded to the latest nightly and seeing the same behavior.  I'm running julia with 8 threads btw.
EDIT2:
I'm also getting errors with `pmap` and `bmap`, but `qmap` looks fine.

**Comment by robsmith11** [comment]
Sorry, it turns out another installed package had caused installing ThreadPools to use a very old version.  Forcing the latest release of ThreadPools fixed this issue.

**Comment by tro3** [comment]
No worries. Well-timed - I was just about to dive in. :-). Thx
