### ISSUE TITLE
Don't export `results`?

### ISSUE THREAD

**Issue by IanButterworth** [tro3/ThreadPools.jl#24]
I typically use `using` and was surprised to see that ThreadPools exports `results` which is a very generic name to export.

Just a suggestion, but perhaps if that needs to be exported, it could have a less generic name?

**Comment by tro3** [comment]
Actually, that just looks like a cut & paste issue or something.  Zero reason to export that.  I will fix.

**Comment by tro3** [comment]
Oh, that is an actual function.  You're right - it is too generic - changing it to `poolresults` will be API-breaking.  But so be it.

**Comment by IanButterworth** [comment]
Thanks!

**Comment by tro3** [comment]
Rev 2.0.0 is making its way through the system
