### ISSUE TITLE
Not working with `continue` keyword

### ISSUE THREAD

**Issue by sairus7** [tro3/ThreadPools.jl#25]
```julia
@qbthreads for x in 1:3
    if x == 2
        continue
    end
    println("$x $(Threads.threadid())")
end
```
Output:
```
ERROR: LoadError: syntax: break or continue outside loop
```

**Comment by tro3** [comment]
Happens because the contents of the loop are split out among the threads.  But I think I can fix it by wrapping each thread in a `for _tmpvar in [1]`.  Will take a look

**Comment by tro3** [comment]
Now works in version 2.0.1.  Will send to Registrar
