### ISSUE TITLE
[Question] How to know current avilable background worker numbers

### ISSUE THREAD

**Issue by AtsushiSakai** [tro3/ThreadPools.jl#34]
Hi. First of all, thank you for the great OSS!!. I love it.

I'm using `spawnbg()` function to run some busy tasks in the background.
Is there any good way to know the current available background worker numbers?

My understanding is that if more processes are spawned than the actual number of worker threads, 
this `spawnbg` function will wait until the worker threads are free as this comment:
https://github.com/tro3/ThreadPools.jl/blob/44730372b9b00ba38192e5d2850dfe24c20cdbeb/src/spawn_background.jl#L46-L47
but I want to throw an exception instead of it. Is there any good way?

Thanks!!

**Comment by tro3** [comment]
Afraid I don’t know offhand

**Comment by AtsushiSakai** [comment]
OK. Thanks!!
