### ISSUE TITLE
Add `@spawn` equivalent?

### ISSUE THREAD

**Issue by IanButterworth** [tro3/ThreadPools.jl#4]
It would be great to be able to `Threads.@spawn` to specific threads, or at least, not thread 1.

Perhaps `@bgspawn` `@fgspawn`?

or expanding upon `Threads.@spawn` and supporting specific thread targets:

```
@spawn 1 gui()
@spawn 2 looper1()
@spawn 3 looper2()
@spawn 3 looper3()
```
```
@spawn 1 gui()
@spawn 2:nthreads() looper1()
@spawn 2:nthreads() looper2()
@spawn 2:nthreads() looper3()
```

Cross-referencing an issue I opened on base. https://github.com/JuliaLang/julia/issues/34240

**Comment by IanButterworth** [comment]
Btw, thanks for this package! I'm hoping this kind of behavior makes it into base eventually

**Comment by tro3** [comment]
> I'm hoping this kind of behavior makes it into base eventually

Thx and agreed.

I am wrapping up v1.0.0 without `@pspawn` and was hoping to add something like this to v1.1.0.  It would not be difficult with the newer API, but there are design decisions to be made.  If we don't mind a pool being pre-created, we can do something like:

```
pwith(SpawnPool()) do pool   # SpawnPool can be configured to which threads are allowed.
  @pspawn pool fn()
  t2 = @pspawn pool fn2()
  wait(t2)
end
```

If we want to manually assign threads, that can be also be done, but sort of defeats the purpose of a pool (whose purpose is to handle the scheduling):

```
task = @pspawnat 2 my_fn()
```

But I personally find the `t2 = @pspawn pool fn2()` kind of unwieldy.  Maybe a macro that simplifies the above, handling passing around the pool:

```
@pwith SpawnPool() begin
  @pspawn fn()
  t2 = @pspawn fn2()
  wait(t2)
end
```

But that gets pretty macro-heavy.  What do you think?

**Comment by IanButterworth** [comment]
I personally need this in 1.3.1 if that makes things complicated?

To be honest, the `@bgspawn` and  `@fgspawn` example macros would be a big improvement over just `@spawn`, and I wouldn't mind not having the choice of which thread specifically.

**Comment by tro3** [comment]
Yes, this will all be Julia 1.3.1.  But I am breaking the API (so moving this pkg to 1.0.0) to have the ability to separate choices around foreground/background and scheduling strategy.  Please take a look at the v1.0.0 branch and see what you think.  I'm hoping to register it this weekend.

**Comment by tro3** [comment]
@ianshmean , in what you are trying to do, are you going to wait for the spawned tasks, or are they open-ended in duration?  (Update: I see the GUI reference above -> open ended)

**Comment by tro3** [comment]
@ianshmean - I will delay an initial 1.0.0 registration to add a `@spawnat` macro that will do what you want. Note that you won’t need to do an `@spawnat 1 gui()` like you have above. The primary will just need `@async gui()`.

**Comment by IanButterworth** [comment]
Ah good point. I thought you meant Julia 1.0, apologies for the confusion.

**Comment by tkf** [comment]
Allow me to step in :)

> Maybe a macro that simplifies the above, handling passing around the pool:
> 
> ```
> @pwith SpawnPool() begin
>   @pspawn fn()
>   t2 = @pspawn fn2()
>   wait(t2)
> end
> ```
> 
> But that gets pretty macro-heavy.

I think you'd need "lexical context handling" anyway if you want to support `@sync`-`@async` pattern. So, I don't think this increases the complexity of `@pspawn`.  It's pretty easy to implement (see the source code of `@sync` and `@async`).

**Comment by tro3** [comment]
@tkf - always happy to hear your opinion. 👍 

I see your point - the background passing of a pool variable here is indeed like the sync variable from `@async/@sync`.  It sounds to me, though, that @ianshmean just wants a more `@spawn`-like launch-and-leave.  There is no "waiting for the end" of the task intended, so we are getting back to the structured concurrency thing.

For now, I'll just add a `@spawnat` to handle the case.  The `@pwith` macro combined with the `@q/b/qbthreads` macros might be something to think about adding, too.  Its a little cleaner than what I have now, but it would only support `@b/q/qbthreads` not `pmap`.

BTW, if you want to take a look at the v1.0.0 branch, I can hold off registering until you give some feedback.  Just let me know.

**Comment by tro3** [comment]
Hmm, though one problem with looking at 1.0.0 is that the documentation/html are in place, but there is no way to webhost it (that I know of) because it is not yet on master.

**Comment by tro3** [comment]
`@spawnat` and tests/docs added to v1.0.0

**Comment by tro3** [comment]
Guys - the `master` branch is now at v1.0.0, if you want to have a look.  I'll register it either later this weekend or after I incorporate any feedback you all have.

**Comment by IanButterworth** [comment]
😍 
```
julia> t = @spawnat 4 Threads.threadid()
Task (runnable) @0x0000000010743c70

julia> fetch(t)
4
```
This is great! Thanks so much

**Comment by IanButterworth** [comment]
I wonder whether this could have a simpler error message through an `@assert`?

```
julia> Threads.nthreads()
6

julia> t = @spawnat 7 Threads.threadid()
ERROR: BoundsError: attempt to access 6-element Array{Base.InvasiveLinkedListSynchronized{Task},1} at index [7]
Stacktrace:
 [1] getindex at ./array.jl:744 [inlined]
 [2] enq_work(::Task) at ./task.jl:497
 [3] schedule(::Task) at ./task.jl:511
 [4] top-level scope at /Users/ian/.julia/packages/ThreadPools/wEWKI/src/macros.jl:265
```

**Comment by IanButterworth** [comment]
Obviously when targeting a thread, one would/should ensure they're targeting something in the range `1:nthreads()`, but it might be helpful to say something like 
```
Thread 7 not available. 7 is not in the range 1:Threads.nthreads() (1:6)
```

**Comment by tro3** [comment]
Agreed.  (The dangers of the last-second addition.)  I'll add a check.

**Comment by tro3** [comment]
Added.  Will wait to merge until any other feedback wraps up, just before register.

```
julia> @spawnat 5 1
ERROR: AssertionError: @spawnat thread assignment (5) must be between 1 and Threads.nthreads() (1:4)
Stacktrace:
[...]
```

**Comment by IanButterworth** [comment]
Looks good to me!

**Comment by IanButterworth** [comment]
By the way, it is possible to do multithreaded testing on travis, if you wanted CI. Example [here](https://github.com/r3tex/ObjectDetector.jl/blob/master/.travis.yml)

**Comment by tro3** [comment]
Nice - thx!  I was planning on adding Travis and Coveralls in an upcoming patch. Now I have a starting point. :-)

**Comment by IanButterworth** [comment]
Just a quick thought.. Is this new behavior closer to `Threads.@spawn` in nature than `@spawnat`? Perhaps it should overload `@spawn`? At least that's where I guess it would go if/when it makes it into base, given `@spawn` is the highlighted method in the base docs along side `Threads.@threads`

**Comment by tro3** [comment]
It is definitely very close to `@spawn`.  I haven’t used `@spawnat`, but assumed it was just like this. The intent wasn’t really to overload either - I wonder if it should be `@pspawnat` or `@pspawn`

**Comment by IanButterworth** [comment]
Thinking about the actual wording here, spawnat is specific, spawn is nonspecific. And not overloading makes sense. 

I’d go for `@pspawnat`

**Comment by IanButterworth** [comment]
I've been testing this ~~and the current overloading of `@spawnat` seems to make loading this unstable.~~ (Edit.. this was a version confusion between environments.. I didn't realized I had ThreadPools 0.2.0 in my main env) 
Would it be possible to push the assert check and the rename to `@pspawnat` so I can test? thanks

**Comment by tro3** [comment]
@ianshmean - done.  Let me know how it looks.

**Comment by IanButterworth** [comment]
Looks good to me! Looking forward to the release :) thanks again
