### ISSUE TITLE
Remove ::Function restrictions?

### ISSUE THREAD

**Issue by tkf** [tro3/ThreadPools.jl#6]
Re:

https://github.com/tro3/ThreadPools.jl/blob/943e83138561a31a1c154749ff12cc32d5c2e104/src/interface.jl#L9-L10

https://github.com/tro3/ThreadPools.jl/blob/943e83138561a31a1c154749ff12cc32d5c2e104/src/interface.jl#L47-L48

I'd suggest removing the restriction `::Function` from `pforeach(fn::Function, pool, itr)` etc. since any object in Julia can be a callable.  For relevant discussions, see https://github.com/JuliaLang/julia/pull/34296 and https://github.com/JuliaLang/julia/pull/30382.  I think [this comment by JeffBezanson](https://github.com/JuliaLang/julia/pull/34296#issuecomment-575299420) is a nice summary (emphasis by me):

> With multiple dispatch, just as the meaning of a function is important to get consistent, **it's also important to get the meanings of the argument slots consistent when possible**. It's not ideal for a function to treat an argument in a fundamentally different way based on its type: e.g. "if this is a Function, then call it on pairs of values, otherwise assume it's a container providing the values to use".

This makes having `pforeach(pool, fn::Function, itr)` a bit an uneasy choice.  I think deprecating this method in 1.1 is a reasonable choice.

**Comment by tro3** [comment]
This one fell off my radar when I got busy the last few months.  I am okay with the above, but how would the compiler differentiate `pforeach(pool, fn::Function, itr)` from `pforeach(fn::Function, pool, itr)`?  I suppose `pool` could be typed.

**Comment by tkf** [comment]
Dispatching on a `pool` type sounds good to me.  But this is tricky so that's why I recommended deprecating `pforeach(pool, fn, itr)`.  It's also what Jeff's comment is all about.
